name: CI-CD Preview

on:
  push:
    branches:
      - dev

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

permissions:
  contents: write
  packages: write

jobs:
  build-and-push:
    name: Build and push docker image
    runs-on: ubuntu-latest

    steps:
      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Setup buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.ref_type == 'tag' && github.ref_name ||  github.sha }}
          cache-from: type=gha,ref=${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=gha,ref=${{ env.IMAGE_NAME }}:buildcache,mode=max

  update-gitops:
    name: Update gitops repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gitops repository
        uses: actions/checkout@v4
        with:
          repository: isd-sgcu/isd-gitops
          token: ${{ secrets.GITOPS_TOKEN }}

      - name: Update image tag
        uses: mikefarah/yq@master
        env:
          NEW_TAG: ${{ github.ref_type == 'tag' && github.ref_name ||  github.sha }}
        with:
          cmd: yq -i '.frontend.imageTag = strenv(NEW_TAG)' projects/openhouse/values/dev.values.yaml

      - name: Commit & Push changes
        uses: actions-js/push@v1.4
        with:
          github_token: ${{ secrets.GITOPS_TOKEN }}
          repository: isd-sgcu/isd-gitops
